//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AttendanceManagement.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudnetAttendance
    {
        public int Statusno { get; set; }
        public Nullable<int> Rollno { get; set; }
        public string StudentName { get; set; }
        public string DateOfClass { get; set; }
        public string AttendanceStatus { get; set; }
        public Nullable<int> Courseid { get; set; }
    
        public virtual StudentDetail StudentDetail { get; set; }
    }
}
